### ISSUE TITLE
Is it possible to add something to the tune of a condvar to this crate?

### ISSUE THREAD

**Issue by not-a-seagull** [smol-rs/async-lock#10]
With the underlying `event_listener` mechanism, would it be possible to add a structure like `std::sync::Condvar` to this crate? I would be willing to implement it if it is.

**Comment by zeenix** [comment]
I would like to see that, yes. @taiki-e what do you think?

**Comment by not-a-seagull** [comment]
I realized this niche is basically fulfilled by [event_listener::Event](https://docs.rs/event-listener/2.5.1/event_listener/struct.Event.html), so I'm closing this issue.
