### ISSUE TITLE
Document raison d'etre compared to futures::lock::Mutex

### ISSUE THREAD

**Issue by tamird** [smol-rs/async-lock#16]
A brief comparison with [`futures::lock::Mutex`](https://docs.rs/futures/0.3.15/futures/lock/struct.Mutex.html) would be helpful in evaluating this crate against the more widely-available alternative in the [futures crate](https://crates.io/crates/futures).

Even if there aren't significant difference, it would be useful to call that out.

**Comment by zeenix** [comment]
@tamird Isn't it obvious from the docs?

`futures::Mutex` [docs say](https://docs.rs/futures/0.3.15/futures/lock/struct.Mutex.html#fairness):

> This mutex provides no fairness guarantees. Tasks may not acquire the mutex in the order that they requested the lock, and it’s possible for a single task which repeatedly takes the lock to starve other tasks, which may be left waiting indefinitely.

While `async_lock::Mutex` [docs say](https://docs.rs/async-lock/2.4.0/async_lock/struct.Mutex.html):

> The locking mechanism uses eventual fairness to ensure locking will be fair on average without sacrificing performance. This is done by forcing a fair lock whenever a lock operation is starved for longer than 0.5 milliseconds.

**Comment by tamird** [comment]
There are some non-obvious details not present in the docs. For instance, async_lock::Mutex doesn't use std::lock::Mutex under the hood at all. Presumably there's a good reason for that, and it would be good to document that reason.

**Comment by zeenix** [comment]
> For instance, async_lock::Mutex doesn't use std:lock:Mutex under the hood at all.

I guess you meant `std::sync::Mutex` but that's an internal detail (maybe it'll use it in the future) that's not relevant to the user. What's relevant is the external behavior and the difference there is pretty obvious to me.

**Comment by tamird** [comment]
Sure. It would be useful to say that they otherwise behave the same; that's not so obvious (and maybe it's a bigger statement than you'd comfortably make? again, not obvious to me).

**Comment by zeenix** [comment]
I'm not sure what you are asking for, tbh. You asked for documentation on how `async_lock::Mutex` differentiates from `futures::lock::Mutex` and I pointed out how that already exists. Now you're saying that we should also document where it's the same? I wouldn't have any objections on making things clearer but since I'm not sure what you're asking for exactly, I think it'd be better if you submit a PR. I'm closing this but if you do submit a PR, please re-open it.

**Comment by wngr** [comment]
What might be note worthy though is that on `wasm32` targets there's no fairness guarantee at all.
