### ISSUE TITLE
`SemaphoreGuard::acquire_arc` busy waits since 2.7.0/#34

### ISSUE THREAD

**Issue by SNCPlay42** [smol-rs/async-lock#41]
The problem is `&mut this.listener.take()` here:

https://github.com/smol-rs/async-lock/blob/f738cfd068ec3e1a6d2de9785571ce1b52b34871/src/semaphore.rs#L231-L239

Since this borrows a temporary expression, `*listener = Some(...` does not actually write to `this.listener`, so the `Some` arm is never taken and the function can never return `Poll::Pending`, instead busy waiting until `try_acquire_arc` succeeds. In my program this seemed to cause an indefinite hang.

The line should just be `match &mut this.listener` like [it is in the non-`Arc` acquire](https://github.com/smol-rs/async-lock/blob/f738cfd068ec3e1a6d2de9785571ce1b52b34871/src/semaphore.rs#L185).

**Comment by notgull** [comment]
Thanks for the catch! Do you mind filing a PR?
