### ISSUE TITLE
A question about poisoning

### ISSUE THREAD

**Issue by A248** [smol-rs/async-lock#53]
I am simply curious regarding why the locks in this library don't implement lock poisoning like those in the standard library. I'm using `RwLock` whose `read` and `write` locking methods are entirely error-free. What was the reasoning behind this design decision?

**Comment by notgull** [comment]
I wasn't around when the library was designed, but I think that not having poisoning makes the library simpler overall.

**Comment by notgull** [comment]
I do not plan on adding poisoning to this library. It could probably be implemented in a higher-level library on top of this one.
