### ISSUE TITLE
Using OnceCell makes caller not Send

### ISSUE THREAD

**Issue by sophie-h** [smol-rs/async-lock#77]
I have a glocal `static` with an `async_lock::OnceCell`. Calls to `set()` or `get_or_init()` make the Future not `Send`.

The same code works with tokio's OnceCell and a similar `async_lock::Mutex` code does as well. As far as I can tell it is independent from the type inside the cell.

Is it possible to fix this problem?

**Comment by taiki-e** [comment]
Duplicate of https://github.com/smol-rs/event-listener-strategy/issues/13
